version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: aflashyrhetoric/payup-api:dev
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      # gin runs on 8114
      - "80:8114"
#     networks:
#       - webnet
# networks:
#   webnet: